maps:
  '113':
    url: https://raw.githubusercontent.com/talax16/OSCity_public/main/assets/congrats.png
    row: 0
    col: 0
    totalRows: 4
    totalCols: 6
  '114':
    url: https://raw.githubusercontent.com/talax16/OSCity_public/main/assets/congrats.png
    row: 0
    col: 1
    totalRows: 4
    totalCols: 6
  '115':
    url: https://raw.githubusercontent.com/talax16/OSCity_public/main/assets/congrats.png
    row: 0
    col: 2
    totalRows: 4
    totalCols: 6
  '116':
    url: https://raw.githubusercontent.com/talax16/OSCity_public/main/assets/congrats.png
    row: 0
    col: 3
    totalRows: 4
    totalCols: 6
  '117':
    url: https://raw.githubusercontent.com/talax16/OSCity_public/main/assets/congrats.png
    row: 0
    col: 4
    totalRows: 4
    totalCols: 6
  '118':
    url: https://raw.githubusercontent.com/talax16/OSCity_public/main/assets/congrats.png
    row: 0
    col: 5
    totalRows: 4
    totalCols: 6
  '119':
    url: https://raw.githubusercontent.com/talax16/OSCity_public/main/assets/congrats.png
    row: 1
    col: 0
    totalRows: 4
    totalCols: 6
  '120':
    url: https://raw.githubusercontent.com/talax16/OSCity_public/main/assets/congrats.png
    row: 1
    col: 1
    totalRows: 4
    totalCols: 6
  '121':
    url: https://raw.githubusercontent.com/talax16/OSCity_public/main/assets/congrats.png
    row: 1
    col: 2
    totalRows: 4
    totalCols: 6
  '122':
    url: https://raw.githubusercontent.com/talax16/OSCity_public/main/assets/congrats.png
    row: 1
    col: 3
    totalRows: 4
    totalCols: 6
  '123':
    url: https://raw.githubusercontent.com/talax16/OSCity_public/main/assets/congrats.png
    row: 1
    col: 4
    totalRows: 4
    totalCols: 6
  '124':
    url: https://raw.githubusercontent.com/talax16/OSCity_public/main/assets/congrats.png
    row: 1
    col: 5
    totalRows: 4
    totalCols: 6
  '125':
    url: https://raw.githubusercontent.com/talax16/OSCity_public/main/assets/congrats.png
    row: 2
    col: 0
    totalRows: 4
    totalCols: 6
  '126':
    url: https://raw.githubusercontent.com/talax16/OSCity_public/main/assets/congrats.png
    row: 2
    col: 1
    totalRows: 4
    totalCols: 6
  '127':
    url: https://raw.githubusercontent.com/talax16/OSCity_public/main/assets/congrats.png
    row: 2
    col: 2
    totalRows: 4
    totalCols: 6
  '128':
    url: https://raw.githubusercontent.com/talax16/OSCity_public/main/assets/congrats.png
    row: 2
    col: 3
    totalRows: 4
    totalCols: 6
  '129':
    url: https://raw.githubusercontent.com/talax16/OSCity_public/main/assets/congrats.png
    row: 2
    col: 4
    totalRows: 4
    totalCols: 6
  '130':
    url: https://raw.githubusercontent.com/talax16/OSCity_public/main/assets/congrats.png
    row: 2
    col: 5
    totalRows: 4
    totalCols: 6
  '131':
    url: https://raw.githubusercontent.com/talax16/OSCity_public/main/assets/congrats.png
    row: 3
    col: 0
    totalRows: 4
    totalCols: 6
  '132':
    url: https://raw.githubusercontent.com/talax16/OSCity_public/main/assets/congrats.png
    row: 3
    col: 1
    totalRows: 4
    totalCols: 6
  '133':
    url: https://raw.githubusercontent.com/talax16/OSCity_public/main/assets/congrats.png
    row: 3
    col: 2
    totalRows: 4
    totalCols: 6
  '134':
    url: https://raw.githubusercontent.com/talax16/OSCity_public/main/assets/congrats.png
    row: 3
    col: 3
    totalRows: 4
    totalCols: 6
  '135':
    url: https://raw.githubusercontent.com/talax16/OSCity_public/main/assets/congrats.png
    row: 3
    col: 4
    totalRows: 4
    totalCols: 6
  '136':
    url: https://raw.githubusercontent.com/talax16/OSCity_public/main/assets/congrats.png
    row: 3
    col: 5
    totalRows: 4
    totalCols: 6
  '149':
    url: https://raw.githubusercontent.com/talax16/OSCity_public/main/assets/disk_table.png
    row: 0
    col: 0
    totalRows: 3
    totalCols: 3
  '150':
    url: https://raw.githubusercontent.com/talax16/OSCity_public/main/assets/disk_table.png
    row: 0
    col: 1
    totalRows: 3
    totalCols: 3
  '151':
    url: https://raw.githubusercontent.com/talax16/OSCity_public/main/assets/disk_table.png
    row: 0
    col: 2
    totalRows: 3
    totalCols: 3
  '152':
    url: https://raw.githubusercontent.com/talax16/OSCity_public/main/assets/disk_table.png
    row: 1
    col: 0
    totalRows: 3
    totalCols: 3
  '153':
    url: https://raw.githubusercontent.com/talax16/OSCity_public/main/assets/disk_table.png
    row: 1
    col: 1
    totalRows: 3
    totalCols: 3
  '154':
    url: https://raw.githubusercontent.com/talax16/OSCity_public/main/assets/disk_table.png
    row: 1
    col: 2
    totalRows: 3
    totalCols: 3
  '155':
    url: https://raw.githubusercontent.com/talax16/OSCity_public/main/assets/disk_table.png
    row: 2
    col: 0
    totalRows: 3
    totalCols: 3
  '156':
    url: https://raw.githubusercontent.com/talax16/OSCity_public/main/assets/disk_table.png
    row: 2
    col: 1
    totalRows: 3
    totalCols: 3
  '157':
    url: https://raw.githubusercontent.com/talax16/OSCity_public/main/assets/disk_table.png
    row: 2
    col: 2
    totalRows: 3
    totalCols: 3
  '3361':
    url: https://raw.githubusercontent.com/talax16/OSCity_public/main/assets/page_table.png
    row: 0
    col: 0
    totalRows: 1
    totalCols: 1
  '3362':
    url: https://raw.githubusercontent.com/talax16/OSCity_public/main/assets/page_table.png
    row: 0
    col: 0
    totalRows: 2
    totalCols: 3
  '3363':
    url: https://raw.githubusercontent.com/talax16/OSCity_public/main/assets/page_table.png
    row: 0
    col: 1
    totalRows: 2
    totalCols: 3
  '3364':
    url: https://raw.githubusercontent.com/talax16/OSCity_public/main/assets/page_table.png
    row: 0
    col: 2
    totalRows: 2
    totalCols: 3
  '3365':
    url: https://raw.githubusercontent.com/talax16/OSCity_public/main/assets/page_table.png
    row: 1
    col: 0
    totalRows: 2
    totalCols: 3
  '3366':
    url: https://raw.githubusercontent.com/talax16/OSCity_public/main/assets/page_table.png
    row: 1
    col: 1
    totalRows: 2
    totalCols: 3
  '3367':
    url: https://raw.githubusercontent.com/talax16/OSCity_public/main/assets/page_table.png
    row: 1
    col: 2
    totalRows: 2
    totalCols: 3
  '3368':
    url: https://raw.githubusercontent.com/talax16/OSCity_public/main/assets/page_table.png
    row: 0
    col: 0
    totalRows: 2
    totalCols: 3
  '3369':
    url: https://raw.githubusercontent.com/talax16/OSCity_public/main/assets/page_table.png
    row: 0
    col: 1
    totalRows: 2
    totalCols: 3
  '3370':
    url: https://raw.githubusercontent.com/talax16/OSCity_public/main/assets/page_table.png
    row: 0
    col: 2
    totalRows: 2
    totalCols: 3
  '3371':
    url: https://raw.githubusercontent.com/talax16/OSCity_public/main/assets/page_table.png
    row: 1
    col: 0
    totalRows: 2
    totalCols: 3
  '3372':
    url: https://raw.githubusercontent.com/talax16/OSCity_public/main/assets/page_table.png
    row: 1
    col: 1
    totalRows: 2
    totalCols: 3
  '3373':
    url: https://raw.githubusercontent.com/talax16/OSCity_public/main/assets/page_table.png
    row: 1
    col: 2
    totalRows: 2
    totalCols: 3
  '3374':
    url: https://raw.githubusercontent.com/talax16/OSCity_public/main/assets/page_table.png
    row: 0
    col: 0
    totalRows: 2
    totalCols: 3
  '3375':
    url: https://raw.githubusercontent.com/talax16/OSCity_public/main/assets/page_table.png
    row: 0
    col: 1
    totalRows: 2
    totalCols: 3
  '3376':
    url: https://raw.githubusercontent.com/talax16/OSCity_public/main/assets/page_table.png
    row: 0
    col: 2
    totalRows: 2
    totalCols: 3
  '3377':
    url: https://raw.githubusercontent.com/talax16/OSCity_public/main/assets/page_table.png
    row: 1
    col: 0
    totalRows: 2
    totalCols: 3
  '3378':
    url: https://raw.githubusercontent.com/talax16/OSCity_public/main/assets/page_table.png
    row: 1
    col: 1
    totalRows: 2
    totalCols: 3
  '3379':
    url: https://raw.githubusercontent.com/talax16/OSCity_public/main/assets/page_table.png
    row: 1
    col: 2
    totalRows: 2
    totalCols: 3
  '3380':
    url: https://raw.githubusercontent.com/talax16/OSCity_public/main/assets/departure_gate.png
    row: 0
    col: 0
    totalRows: 2
    totalCols: 4
  '3381':
    url: https://raw.githubusercontent.com/talax16/OSCity_public/main/assets/departure_gate.png
    row: 0
    col: 1
    totalRows: 2
    totalCols: 4
  '3382':
    url: https://raw.githubusercontent.com/talax16/OSCity_public/main/assets/departure_gate.png
    row: 0
    col: 2
    totalRows: 2
    totalCols: 4
  '3383':
    url: https://raw.githubusercontent.com/talax16/OSCity_public/main/assets/departure_gate.png
    row: 0
    col: 3
    totalRows: 2
    totalCols: 4
  '3384':
    url: https://raw.githubusercontent.com/talax16/OSCity_public/main/assets/departure_gate.png
    row: 1
    col: 0
    totalRows: 2
    totalCols: 4
  '3385':
    url: https://raw.githubusercontent.com/talax16/OSCity_public/main/assets/departure_gate.png
    row: 1
    col: 1
    totalRows: 2
    totalCols: 4
  '3386':
    url: https://raw.githubusercontent.com/talax16/OSCity_public/main/assets/departure_gate.png
    row: 1
    col: 2
    totalRows: 2
    totalCols: 4
  '3387':
    url: https://raw.githubusercontent.com/talax16/OSCity_public/main/assets/departure_gate.png
    row: 1
    col: 3
    totalRows: 2
    totalCols: 4
  '3388':
    url: https://raw.githubusercontent.com/talax16/OSCity_public/main/assets/assessment_room.png
    row: 0
    col: 0
    totalRows: 2
    totalCols: 4
  '3389':
    url: https://raw.githubusercontent.com/talax16/OSCity_public/main/assets/assessment_room.png
    row: 0
    col: 1
    totalRows: 2
    totalCols: 4
  '3390':
    url: https://raw.githubusercontent.com/talax16/OSCity_public/main/assets/assessment_room.png
    row: 0
    col: 2
    totalRows: 2
    totalCols: 4
  '3391':
    url: https://raw.githubusercontent.com/talax16/OSCity_public/main/assets/assessment_room.png
    row: 0
    col: 3
    totalRows: 2
    totalCols: 4
  '3392':
    url: https://raw.githubusercontent.com/talax16/OSCity_public/main/assets/assessment_room.png
    row: 1
    col: 0
    totalRows: 2
    totalCols: 4
  '3393':
    url: https://raw.githubusercontent.com/talax16/OSCity_public/main/assets/assessment_room.png
    row: 1
    col: 1
    totalRows: 2
    totalCols: 4
  '3394':
    url: https://raw.githubusercontent.com/talax16/OSCity_public/main/assets/assessment_room.png
    row: 1
    col: 2
    totalRows: 2
    totalCols: 4
  '3395':
    url: https://raw.githubusercontent.com/talax16/OSCity_public/main/assets/assessment_room.png
    row: 1
    col: 3
    totalRows: 2
    totalCols: 4
  '3396':
    url: https://raw.githubusercontent.com/talax16/OSCity_public/main/assets/lazy_loading.png
    row: 0
    col: 0
    totalRows: 2
    totalCols: 3
  '3397':
    url: https://raw.githubusercontent.com/talax16/OSCity_public/main/assets/lazy_loading.png
    row: 0
    col: 1
    totalRows: 2
    totalCols: 3
  '3398':
    url: https://raw.githubusercontent.com/talax16/OSCity_public/main/assets/lazy_loading.png
    row: 0
    col: 2
    totalRows: 2
    totalCols: 3
  '3399':
    url: https://raw.githubusercontent.com/talax16/OSCity_public/main/assets/lazy_loading.png
    row: 1
    col: 0
    totalRows: 2
    totalCols: 3
  '3400':
    url: https://raw.githubusercontent.com/talax16/OSCity_public/main/assets/lazy_loading.png
    row: 1
    col: 1
    totalRows: 2
    totalCols: 3
  '3401':
    url: https://raw.githubusercontent.com/talax16/OSCity_public/main/assets/lazy_loading.png
    row: 1
    col: 2
    totalRows: 2
    totalCols: 3
  '3402':
    url: https://raw.githubusercontent.com/talax16/OSCity_public/main/assets/lazy_allocation.png
    row: 0
    col: 0
    totalRows: 2
    totalCols: 3
  '3403':
    url: https://raw.githubusercontent.com/talax16/OSCity_public/main/assets/lazy_allocation.png
    row: 0
    col: 1
    totalRows: 2
    totalCols: 3
  '3404':
    url: https://raw.githubusercontent.com/talax16/OSCity_public/main/assets/lazy_allocation.png
    row: 0
    col: 2
    totalRows: 2
    totalCols: 3
  '3405':
    url: https://raw.githubusercontent.com/talax16/OSCity_public/main/assets/lazy_allocation.png
    row: 1
    col: 0
    totalRows: 2
    totalCols: 3
  '3406':
    url: https://raw.githubusercontent.com/talax16/OSCity_public/main/assets/lazy_allocation.png
    row: 1
    col: 1
    totalRows: 2
    totalCols: 3
  '3407':
    url: https://raw.githubusercontent.com/talax16/OSCity_public/main/assets/lazy_allocation.png
    row: 1
    col: 2
    totalRows: 2
    totalCols: 3
  '3408':
    url: https://raw.githubusercontent.com/talax16/OSCity_public/main/assets/lazy_allocation.png
    row: 0
    col: 0
    totalRows: 2
    totalCols: 3
  '3409':
    url: https://raw.githubusercontent.com/talax16/OSCity_public/main/assets/lazy_allocation.png
    row: 0
    col: 1
    totalRows: 2
    totalCols: 3
  '3410':
    url: https://raw.githubusercontent.com/talax16/OSCity_public/main/assets/lazy_allocation.png
    row: 0
    col: 2
    totalRows: 2
    totalCols: 3
  '3411':
    url: https://raw.githubusercontent.com/talax16/OSCity_public/main/assets/lazy_allocation.png
    row: 1
    col: 0
    totalRows: 2
    totalCols: 3
  '3412':
    url: https://raw.githubusercontent.com/talax16/OSCity_public/main/assets/lazy_allocation.png
    row: 1
    col: 1
    totalRows: 2
    totalCols: 3
  '3413':
    url: https://raw.githubusercontent.com/talax16/OSCity_public/main/assets/lazy_allocation.png
    row: 1
    col: 2
    totalRows: 2
    totalCols: 3
  '3414':
    url: https://raw.githubusercontent.com/talax16/OSCity_public/main/assets/lazy_loading.png
    row: 0
    col: 0
    totalRows: 2
    totalCols: 3
  '3415':
    url: https://raw.githubusercontent.com/talax16/OSCity_public/main/assets/lazy_loading.png
    row: 0
    col: 1
    totalRows: 2
    totalCols: 3
  '3416':
    url: https://raw.githubusercontent.com/talax16/OSCity_public/main/assets/lazy_loading.png
    row: 0
    col: 2
    totalRows: 2
    totalCols: 3
  '3417':
    url: https://raw.githubusercontent.com/talax16/OSCity_public/main/assets/lazy_loading.png
    row: 1
    col: 0
    totalRows: 2
    totalCols: 3
  '3418':
    url: https://raw.githubusercontent.com/talax16/OSCity_public/main/assets/lazy_loading.png
    row: 1
    col: 1
    totalRows: 2
    totalCols: 3
  '3419':
    url: https://raw.githubusercontent.com/talax16/OSCity_public/main/assets/lazy_loading.png
    row: 1
    col: 2
    totalRows: 2
    totalCols: 3
  '3420':
    url: https://raw.githubusercontent.com/talax16/OSCity_public/main/assets/page_table.png
    row: 0
    col: 0
    totalRows: 2
    totalCols: 3
  '3421':
    url: https://raw.githubusercontent.com/talax16/OSCity_public/main/assets/page_table.png
    row: 0
    col: 1
    totalRows: 2
    totalCols: 3
  '3422':
    url: https://raw.githubusercontent.com/talax16/OSCity_public/main/assets/page_table.png
    row: 0
    col: 2
    totalRows: 2
    totalCols: 3
  '3423':
    url: https://raw.githubusercontent.com/talax16/OSCity_public/main/assets/page_table.png
    row: 1
    col: 0
    totalRows: 2
    totalCols: 3
  '3424':
    url: https://raw.githubusercontent.com/talax16/OSCity_public/main/assets/page_table.png
    row: 1
    col: 1
    totalRows: 2
    totalCols: 3
  '3425':
    url: https://raw.githubusercontent.com/talax16/OSCity_public/main/assets/page_table.png
    row: 1
    col: 2
    totalRows: 2
    totalCols: 3
  '3426':
    url: https://raw.githubusercontent.com/talax16/OSCity_public/main/assets/arrow.png
    row: 0
    col: 0
    totalRows: 1
    totalCols: 1
  '3987':
    url: https://raw.githubusercontent.com/talax16/OSCity_public/main/assets/arrow.png
    row: 0
    col: 0
    totalRows: 1
    totalCols: 1
